Edge cases test for tests/0-add_integer.txt
Testing add_integer() function

>>> add_integer(2, 99)
101

>>> add_integer(-2, -99)
-101

>>> add_integer(3.2, 2.3)
5

>>> add_integer(-3.2, -2.3)
-5

>>> add_integer(8)
106

>>> add_integer(8, )
106

>>> add_integer("test", 3)
Traceback (most recent call last):
...
TypeError: a must be an integer

>>> add_integer(3, "test")
Traceback (most recent call last):
...
TypeError: b must be an integer

>>> add_integer((1,2,3), 3)
Traceback (most recent call last):
...
TypeError: a must be an integer

>>> add_integer(3, (1,2,3))
Traceback (most recent call last):
...
TypeError: b must be an integer

>>> add_integer({1,2,3}, 3)
Traceback (most recent call last):
...
TypeError: a must be an integer

>>> add_integer(3, {1,2,3})
Traceback (most recent call last):
...
TypeError: b must be an integer
